# Generated by Django 5.2.1 on 2025-05-19 09:53

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image_banner', models.ImageField(default='default_article.jpg', upload_to='article_banners/')),
                ('categorie', models.CharField(choices=[('news', 'News'), ('guide', 'Guide'), ('avis', 'Avis')], max_length=50)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bracket_level', models.CharField(choices=[('1', 'Niveau 1'), ('2', 'Niveau 2'), ('3', 'Niveau 3'), ('4', 'Niveau 4'), ('5', 'Niveau 5')], max_length=1)),
                ('format', models.CharField(choices=[('commander', 'Commander'), ('modern', 'Modern'), ('standard', 'Standard')], max_length=50)),
                ('banner_img', models.ImageField(default='default_banner.jpg', upload_to='event_banners/')),
                ('nombre_participant', models.PositiveIntegerField(default=0)),
                ('nombre_participant_max', models.PositiveIntegerField(default=2)),
                ('date', models.DateTimeField()),
                ('IRL', models.BooleanField(default=False)),
                ('lieux', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positif', models.BooleanField()),
                ('commentaire', models.TextField()),
                ('date_poste', models.DateTimeField(auto_now_add=True)),
                ('banned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=models.SET(events.models.get_sentinel_user), related_name='avis_events', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.URLField(help_text='Lien vers le deck (Moxfield ou MagicVille)')),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
