# Generated by Django 5.2.1 on 2025-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nombre_participant_max',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='nombre_participant',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
