# Generated by Django 5.2.1 on 2025-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('commander', 'Commander'), ('modern', 'Modern'), ('standard', 'Standard'), ('draft', 'Draft'), ('sealed', 'Sealed')], max_length=50),
        ),
    ]
