# Generated by Django 5.2.1 on 2025-05-14 07:54

import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisevent',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(events.models.get_sentinel_user), related_name='avis_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
